version: "3"
services:
    web:
        build:
            context: ./web
        image: tokyomap.web:dev
        container_name: tokyomap-web
        volumes:
            - "./web/public:/usr/share/nginx" # todo: hot reload
            - "./web/logs:/var/log/nginx"
        ports:
            - "443:443"
