version: "3"
services:
    web:
        build:
            context: ./web
        image: tokyomap.web:dev
        container_name: tokyomap-web
        volumes:
            - "./public:/usr/share/nginx"
            - "./web/certs:/etc/ssl/certs"
            - "./web/logs:/var/log/nginx"
            - "./web/dev.conf:/etc/nginx/conf.d/dev.conf"
        ports:
            - "443:443"
