import { createSlice, createAction, PayloadAction } from '@reduxjs/toolkit';

/**
 * Redux state + actions for the socket feature, built with Redux Toolkit.
 *
 * Two kinds of actions live here:
 * - the slice action (tweetsReceived) which actually CHANGES this state
 * - standalone createAction signals (connectToSocket / postTweet / connectToSocketFailed) which change NO state and exist only to drive socketSaga.
 */

/** Payload of a tweet the user submits (sent to the server via the saga). */
export interface TweetPosted {
  userId: string;
  message: string;
  geolocation: L.LatLngTuple;
}

/** The socket slice's state: the tweets currently shown on the map. */
export interface SocketState {
  tweets: Tweet[];
}

export const initialSocketState: SocketState = { tweets: [] };

/**
 * createSlice generates, from one definition, the reducer + the action creators + their type strings for this state.
 * Here it defines the single state-changing action, `tweetsReceived`.
 */
const socketSlice = createSlice({
  name: 'socket',
  initialState: initialSocketState,
  reducers: {
    // the server pushed the current tweets (on connect, or after a post) — replace them in state
    tweetsReceived: (state, action: PayloadAction<Tweet[]>) => ({ ...state, tweets: action.payload }),
  },
});

/**
 * Action creator generated by the slice above; dispatched by the saga when tweets arrive.
 */
export const { tweetsReceived } = socketSlice.actions;

/**
 * Saga-only signals.
 * createAction makes a standalone action creator from a type string, so these are dispatchable and the saga can take() them:
 * - connectToSocket: "open the socket" (dispatched by the map container on mount)
 * - connectToSocketFailed: "the connection failed" (dispatched on error)
 * - postTweet: "send this tweet" (dispatched by ModalTweet; carries the TweetPosted payload)
 */
export const connectToSocket = createAction('socket/connect');
export const connectToSocketFailed = createAction('socket/connectFailed');
export const postTweet = createAction<TweetPosted>('socket/postTweet');

/**
 * The actions the socket event channel can emit into the store (used to type subscriber/saga).
 */
export type SocketEvent =
  | ReturnType<typeof tweetsReceived>
  | ReturnType<typeof connectToSocketFailed>;

/**
 * The slice's reducer, handed to the store.
 */
export default socketSlice.reducer;
