# check validation by "circleci config validate -c .circleci/config.yml"
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
executors:
  default:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/workspace  
jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run: 
          name: Install node modules
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/install
      - run:
          name: List public/
          command: |
            ls -lFa public
      - run:
          name: Deploy to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync ~/workspace/public s3://${AWS_S3_BUCKET_NAME} --exact-timestamps --delete --exclude "report.html" --acl private
              exit;
            fi
            aws s3 sync ~/workspace/public s3://${AWS_S3_BUCKET_NAME_TEST} --exact-timestamps --delete --exclude "report.html" --acl private
workflows:
  version: 2
  build_and_deploy:
    jobs:
      # - test
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
          requires:
            - build
