export const GetGeolocationType = {
  GET_GEOLOCATION_BEGIN: 'GET_GEOLOCATION/BEGIN',
  GET_GEOLOCATION_RESOLVE: 'GET_GEOLOCATION/RESOLVE',
  GET_GEOLOCATION_REJECT: 'GET_GEOLOCATION/REJECT',
} as const;
