export const ConnectToSocketType = {
  CONNECT_TO_SOCKET_BEGIN: 'CONNECT_TO_SOCKET/BEGIN',
  CONNECT_TO_SOCKET_RESOLVE: 'CONNECT_TO_SOCKET/RESOLVE',
  CONNECT_TO_SOCKET_REJECT: 'CONNECT_TO_SOCKET/REJECT',
} as const;

export const GetGeolocationType = {
  GET_GEOLOCATION_BEGIN: 'GET_GEOLOCATION/BEGIN',
  GET_GEOLOCATION_RESOLVE: 'GET_GEOLOCATION/RESOLVE',
  GET_GEOLOCATION_REJECT: 'GET_GEOLOCATION/REJECT',
} as const;

export const PostTweetType = {
  POST_TWEET_BEGIN: 'POST_TWEET/BEGIN',
  POST_TWEET_RESOLVE: 'POST_TWEET/RESOLVE',
  POST_TWEET_REJECT: 'POST_TWEET/REJECT',
} as const;
