export const ConnectSocketType = {
  CONNECT_SOCKET_BEGIN: 'CONNECT/SOCKET/BEGIN',
  CONNECT_SOCKET_RESOLVE: 'CONNECT/SOCKET/RESOLVE',
  CONNECT_SOCKET_REJECT: 'CONNECT/SOCKET/REJECT',
} as const;

export const GetGeolocationType = {
  GET_GEOLOCATION_BEGIN: 'SOCKET/GET/GEOLOCATION/BEGIN',
  GET_GEOLOCATION_RESOLVE: 'SOCKET/GET/GEOLOCATION/RESOLVE',
  GET_GEOLOCATION_REJECT: 'SOCKET/GET/GEOLOCATION/REJECT',
} as const;

export const PostTweetType = {
  POST_TWEET_BEGIN: 'POST/TWEET/BEGIN',
  POST_TWEET_RESOLVE: 'POST/TWEET/RESOLVE',
  POST_TWEET_REJECT: 'POST/TWEET/REJECT',
} as const;
