export const ConnectToSocketType = {
  CONNECT_TO_SOCKET_BEGIN: 'CONNECT_TO_SOCKET/BEGIN',
  CONNECT_TO_SOCKET_RESOLVE: 'CONNECT_TO_SOCKET/RESOLVE',
  CONNECT_TO_SOCKET_REJECT: 'CONNECT_TO_SOCKET/REJECT',
} as const;

export const PostTweetType = {
  POST_TWEET_BEGIN: 'POST_TWEET/BEGIN',
  POST_TWEET_RESOLVE: 'POST_TWEET/RESOLVE',
  POST_TWEET_REJECT: 'POST_TWEET/REJECT',
} as const;
